services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=registrarmysql.mysql.database.azure.com
      - DB_PORT=3306
      - DB_USER=Artin@registrarmysql
      - DB_PASSWORD=@Rtin1382
      - DB_NAME=registrar
    volumes:
      - ./DigiCertGlobalRootCA.crt.pem:/app/DigiCertGlobalRootCA.crt.pem

networks:
  default:
    driver: bridge
